/*
 * This source file was generated by the Gradle 'init' task
 */
package org

import org.days.*
import org.helpers.*

fun main(){
    AdventOfCode()
}

class AdventOfCode() : LoggerAware(){
    init {
        while(true){
            log.info("--------------------select a day--------------------\n")
            val puzzleNumber = readLine()

            when(puzzleNumber){
                "1" -> Day1()
                "2" -> Day2()
                "q" -> break
                else -> log.warn("Puzzle ainda nao implementado")
            }
        }
        System.exit(0)
    }
}